version: "3"
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodapi
  composer:
    image: composer
    volumes:
      - ./:/app
  php:
    build: .
    ports:
      - "1112:1112"
    working_dir: /app
    volumes:
      - ./:/app
